name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Update Fork from Upstream
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for all branches

      - name: Configure Git User
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/Frost-Phoenix/nixos-config.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Checkout origin/master Branch
        run: git checkout master

      - name: Merge Changes
        run: git merge upstream/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Changes
        run: git push origin master

